Myhomepage/Myhp/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^Myinfo/', include('Myinfo.urls')),
url(r'^', include('Myinfo.urls')),
url(r'^Board/', include('Board.urls')),
url(r'^Sendemail/', include('Sendemail.urls')),


]

Myhomepage/Myinfo/urls.py
from django.conf.urls import url
from . import views

app_name='Myinfo'

urlpatterns = [
    url(r'^reg/', views.regPerson, name='reg'),
    url(r'^home/', views.create, name='createP'), #회원정보저장
    url(r'^', views.main, name='main'), #메인화면

]

Myhomepage/Board/models.py
from django.db import models
from Myinfo.models import Myinfo
from datetime import datetime

class Board(models.Model):
	board_num = models.IntegerField()
	board_name = models.CharField(max_length=100)
	board_detail = models.CharField(max_length=300)

	def __str__(self):
		return self.board_name

class Post(models.Model):
	post_num = models.AutoField(primary_key=True)
	board_name = models.ForeignKey(Board, on_delete=models.CASCADE)
	post_name = models.CharField(max_length=100)
	post_detail = models.CharField(max_length=300)
	post_link = models.CharField(max_length=300)
	name = models.ForeignKey(Myinfo, on_delete=models.CASCADE)
	post_write = models.DateTimeField(default=datetime.now)
	post_views = models.IntegerField(default=0)


	def __str__(self):
		return self.post_name

Myhomepage/Myinfo/models.py
from django.db import models

# Create your models here.

class Myinfo(models.Model):
	name = models.CharField(max_length=30)
	photo = models.CharField(max_length=500, null=True, blank=True)
	email = models.CharField(max_length=100)
	github_link = models.CharField(max_length=100)
	skill = models.CharField(max_length=500)
	sns = models.CharField(max_length=100)
	introduction = models.CharField(max_length=1000)

	def __str__(self):
		return self.name

Myhomepage/Sendemail/models.py
from django.db import models
from Myinfo.models import Myinfo

class Sendemail(models.Model):
	email = models.CharField(max_length=30, default="jje0ng@kookmin.ac.kr")
	Outemail = models.CharField(max_length=100)
	content = models.CharField(max_length=1000)

Myhomepage/Myinfo/forms.py
from django.forms import ModelForm
from .models import Myinfo

class MyinfoForm(ModelForm):
    class Meta:
        model = Myinfo
        fields = ['name','photo','email','github_link','skill','sns','introduction']

Myhomepage/Board/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import BoardForm
from .forms import PostForm

def postview(request,post_id):
    #your code
    Post.post_views=Post.post_views+1
    Post.post_views.save()
    #your code

def create(request): #게시글작성하고db에저장되는부분
    if request.method=='POST':
        form =BoardForm(request.POST)
        if form.is_valid():
            form.save() #db에 저장하는부분
        # return redirect('/Myinfo/list')
    else: ##데이터입력폼
        form = BoardForm()

    return render(request, 'Myinfo/readPerson.html', {'form': form}) 

def Board(request):
    return render(request,'Myinfo/Board.html') #게시판화면보이기

# def makepost(request):
#     return render(request,'Myinfo/main.html') 

Myhomepage/Myinfo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from Myinfo.models import Myinfo
from .models import *
from .forms import MyinfoForm

def main(request):
    return render(request,'Myinfo/main.html')


def regPerson(request):
    return render(request, 'Myinfo/registerPerson.html')
################
# def regConPerson(request):
#     name = request.POST['name']
#     photo = request.POST['photo']
#     email = request.POST['email']
#     github_link = request.POST['github_link']
#     skill = request.POST['skill']
#     sns = request.POST['sns']
#     introduction = request.POST['introduction']
#
#     qp=Myinfo(name=name, photo=photo, email=email, github_link=github_link, skill=skill, sns=sns, introduction=introduction)
#     qp.save() #데이터베이스에저장
#
#     return HttpResponseRedirect(reverse('Myinfo:mainP')) #로그인하면메인화면으로정보넘겨줌
#############
def create(request):
    if request.method=='POST':
        form = MyinfoForm(request.POST)
        if form.is_valid():
            form.save() #db에 저장하는부분
            return redirect('/')
    else:
        form = MyinfoForm()

    return render(request, 'Myinfo/readPerson.html', {'form': form})




##############

# def mainPerson(request):
#     qp = Myinfo.objects.all()
#     context = {'Myinfo_list': qp}
#     return render(request, 'Myinfo/readPerson.html', context)

Myhomepage/Sendemail/views.py
from django.shortcuts import render
from Sendemail.models import Sendemail

admin.site.register(Sendemail)

# Create your views here.

Myhomepage/Myinfo/templates/Myinfo/main.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/myhomep.css' %}">
{% endblock css %}


{% block content %}
<div class="mainpage">
  
        <button id="Register" onclick="location.href='/Myinfo/reg'">Register</button>
        <button id="login">Login</button>


  </div>
{% endblock content %}

Myhomepage/Myinfo/templates/Myinfo/readPerson.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/myhomep.css' %}">
{% endblock css %}

{% block nav %}
<nav>
  <ul>
    <li><a href = "/index.html">HOME</a></li>
    <li><a href = "/Project/Project.html" id='b1'>Project</a></li>
    <li><a href = "/News/News.html">News</a></li>
    <li><a href = "/Contact/Contact.html">Contact</a></li>
  </ul>
</nav>
{% endblock nav %}

{% block content %}

    <div class="bgtext">

      <p>{{form.name}}</p>
      <h2>Kookmin University Software</h2>
      <h3>Contact</h3>
      <h4>{{form.email}}</h4>
      <img src="insta.png" width="25px" height="25px">
      <a href="http://www.instagram.com/iwantyun" target="blank"> {{form.sns}}</h4>

    </div>

{% endblock content %}

Myhomepage/Myinfo/templates/Myinfo/registerPerson.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock css %}

{% block content %}
<div class="reg">
  <p>WELCOME</p>
  
    <form action="{% url 'Myinfo:createP'%}" method="post">{% csrf_token %}

      name : <input type="text" name="name"></br>
      email : <input type="text" name="email"></br>
      github_link : <input type="text" name="github_link"></br>
      skill : <input type="text" name="skill"></br>
      sns : <input type="text" name="sns"></br>
      <input type="submit" name="Register"></br>
    </form>
  </div>

{% endblock content %}

Myhomepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OutaMe</title>
    {% block css %}
    {% endblock css %}
    <!-- <link rel="stylesheet" href="{% static 'css/myhomep.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% block nav %}
    {% endblock nav %}

    {% block content %}
    {% endblock content %}


</body>